### ISSUE TITLE
DarkRP Issue

### ISSUE THREAD

**Issue by dhkatz** [mitterdoo/keeptalkingnobodyexplodes#1]
Not really a problem with the addon, however it does appear to break DarkRP. I know this is not intended for DarkRP, but just letting you know.

**Comment by mitterdoo** [comment]
eugh i reeaally don't like bugs like this, especially with a gamemode i particularly dislike. i gotta head to bed, but in the meantime, are there any errors in the server console? or on your own console when you're playing on it?

**Comment by dhkatz** [comment]
No errors, however it appears that the break is DarkRP failing upon load (data of the players on join).

**Comment by mitterdoo** [comment]
darkrp doesnt work as soon as a player joins or when the bomb entity is spawned?

**Comment by dhkatz** [comment]
When the bomb entity is spawned.

**Comment by mitterdoo** [comment]
okay. i'll try pinpointing the cause of this when i get home today.

**Comment by dhkatz** [comment]
Sweet

**Comment by mitterdoo** [comment]
well, i downloaded DarkRP and booted it up on my server, and spawning the entity is just business as usual. i don't see any noticeable problems. it could very well be the method of networking everything from just the entity itself, which i plan on changing eventually.
